# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eb9fe273979bd0648a9b8e302aad4420955c9a6dd166000b063d45261126b47fef47a6e909a989466af7a324b56a91a593aab5130690e356338767a72112e18b

test:
  secret_key_base: 24998e03bf5c436fbc64896c7d9990e87c1139de5357e77cc40422d91a52caae5899ef4c8eba18b4f84f817accd3fc6b5ba64fda6bf4dfee1f0745fb24510784

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
